data_source dbsource:  
    type: snowflake
    account: cl31586.central-india.azure
    username: prabhus
    password: Sastika@2023
    role: accountadmin
    database: SNOWFLAKE_SAMPLE_DATA
    warehouse: compute_wh
    schema: TPCH_SF10
    threads: 10
    client_session_keep_alive: False
soda_cloud:
  host: cloud.soda.io
  api_key_id: 782cfa87-e03b-442c-bff7-bfd85be0d7cf
  api_key_secret: 2L7gPUXOw8MmW66D8Yi0T5bZXNP-IjRpRyMG9nNP_lE3-IgO3gKvww 
